# version: "3.8"
services:
  doemain-db:
    image: postgres:latest
    container_name: doemain-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: 'bob'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'doe-project'

  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    # ports:
    #   - 3000:3000
    networks:
      - app-network
    environment:
      - REACT_APP_API_BASE_URL=http://localhost
    depends_on:
      - backend

  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    # ports:
    #   - 5000:5000
    networks:
      - app-network
    environment:
      - JWT_SECRET_KEY=X6vOyy2HnYteoT8uRd0N8xjwyThGaGav
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - doemain-db

  nginx-main:
    image: nginx:latest
    container_name: nginx-main
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      - doemain-db


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge